insert into BRANCH(NAME, URL) values('Apple','apple');
insert into BRANCH(NAME, URL) values('Samsung','samsung');
insert into BRANCH(NAME, URL) values('Xiaomi','xiaomi');
insert into BRANCH(NAME, URL) values('Oppo','oppo');
insert into BRANCH(NAME, URL) values('Asus','asus');
insert into CATEGORY(NAME, URL) values('Điện thoại','dien-thoai');
insert into CATEGORY(NAME, URL) values('Máy tính bảng','may-tinh-bang');
insert into CATEGORY(NAME, URL) values('Tai nghe','tai-nghe');
insert into CATEGORY(NAME, URL) values('Pin, sạc dự phòng','pin-sac-du-phong');
insert into CATEGORY(NAME, URL) values('Dây cáp','day-cap');
insert into CATEGORY(NAME, URL) values('Thẻ nhớ','the-nho');
insert into USERS(USERNAME, PASSWORD, NAME, TYPE) values('admin','$2y$10$D7y74wIFDGmo.0n5WqkjKO.Lmf1zNRL1pwcjqu5slHdK71WCzLEFK','admin',1);
insert into BANNER(URL, PATH, TYPE) values('/dien-thoai/apple/iphone-xr-256gb-moi', 'iphone-xr-banner.jpg', 1001);
insert into BANNER(URL, PATH, TYPE) values('/dien-thoai/xiaomi/xiaomi-mi-8-nhap-khau-ram-6gb-256gb', 'xiaomi-mi8-banner.jpg', 1002);
insert into BANNER(URL, PATH, TYPE) values('/dien-thoai/samsung/samsung-galaxy-s9-plus-han-quoc', 'samsung-s9-banner.jpg', 1);
insert into BANNER(URL, PATH, TYPE) values('/dien-thoai/oppo/oppo-a3s-chinh-hang', 'oppo-a3s-banner.png', 2);
insert into BANNER(URL, PATH, TYPE) values('/may-tinh-bang/apple/ipad-pro-10-5-64gb-moi-da-kich-hoat', 'ipad-pro-banner.png', 3);